package com.EquiposMedicos.domain;


import jakarta.persistence.*;
import java.sql.Date;
import java.time.LocalDate;
import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

/**
 *
 * @author kcalm
 */

@Data
@Entity
@Table(name = "AlertasMantenimiento")
public class AlertaMantenimiento {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long idAlerta;

    
    
    @ManyToOne
    @JoinColumn(name = "idEquipo", nullable = false)
    private Equipo equipo; // Referencia a la entidad Equipos (clave foránea)
    
    @Temporal(TemporalType.DATE)
    @Column(name = "fechaAlerta", nullable = false)
    private java.sql.Date fechaAlerta; 

    @Column(name = "motivo", length = 255)
    private String motivo; 

    @ManyToOne
    @JoinColumn(name = "idEstado")
    private Estado estado; 
    
    public AlertaMantenimiento(Equipo equipo, Date fechaAlerta, String motivo, Estado estado) {
        this.equipo = equipo;
        this.fechaAlerta = fechaAlerta;
        this.motivo = motivo;
        this.estado = estado;
    }

    public AlertaMantenimiento() {
    }
    
}



//-- Tabla AlertasMantenimiento (depende de Equipos y Estado)
//CREATE TABLE AlertasMantenimiento (
//    idAlerta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//    idEquipo NUMBER NOT NULL,
//    fechaAlerta DATE NOT NULL,
//    motivo VARCHAR2(255),
//    idEstado NUMBER,  -- Estado de la alerta (referencia a la tabla Estado)
//    CONSTRAINT fk_alertas_equipos FOREIGN KEY (idEquipo) REFERENCES Equipos(idEquipo),
//    CONSTRAINT fk_alertas_estado FOREIGN KEY (idEstado) REFERENCES Estado(idEstado)
//);