/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.EquiposMedicos.domain;


import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.*;
import java.io.Serializable;
import java.sql.Date;
import lombok.Data;

/**
 *
 * @author Chope2805
 */
@Data
@Entity
@Table(name = "Componentes")
public class Componentes implements Serializable{
    
      @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long idComponente;

    @ManyToOne
    @JoinColumn(name = "idEquipo", nullable = false)
    private Equipo equipo;

    @Column(nullable = false, length = 100)
    private String nombre;

    @Column(length = 50)
    private String estado;

    @Temporal(TemporalType.DATE)
    private Date fechaInstalacion;

  
    public Componentes(Equipo equipo, String nombre, String estado, Date fechaInstalacion) {
        this.equipo = equipo;
        this.nombre = nombre;
        this.estado = estado;
        this.fechaInstalacion = fechaInstalacion;
    }

    
    public Componentes() {
    }
    /*
    CREATE TABLE Componentes (
    idComponente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idEquipo NUMBER NOT NULL,
    nombre VARCHAR2(100),
    estado VARCHAR2(50),  
    fechaInstalacion DATE,
    CONSTRAINT fk_componentes_equipos FOREIGN KEY (idEquipo) REFERENCES Equipos(idEquipo)
*/
}
