
package com.EquiposMedicos.domain;

import jakarta.persistence.*;
import java.io.Serializable;
import java.sql.Date;
import java.time.LocalDate;

import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

/**
 *
 * @author kcalm
 */
@Data
@Entity
@Table(name = "Equipos")
public class Equipo implements Serializable{

     @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long idEquipo;

    @Column(name = "nombre", length = 100, nullable = false)
    private String nombre;

    @Column(name = "tipo", length = 50)
    private String tipo;

    @Column(name = "fabricante", length = 100)
    private String fabricante;

    @Column(name = "numeroSerie", length = 100)
    private String numeroSerie;

    @Column(name = "fechaAdquisicion")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private LocalDate fechaAdquisicion;

    @ManyToOne
    @JoinColumn(name = "idUbicacion", nullable = false)
    private Ubicacion ubicacion;

    @ManyToOne
    @JoinColumn(name = "idCategoria", nullable = false)
    private CategoriaEquipo categoriaEquipo;

    @ManyToOne
    @JoinColumn(name = "idEstado")
    private Estado estado;

    public Equipo(String nombre, String tipo, String fabricante, String numeroSerie, LocalDate fechaAdquisicion, Ubicacion ubicacion, CategoriaEquipo categoriaEquipo, Estado estado) {
        this.nombre = nombre;
        this.tipo = tipo;
        this.fabricante = fabricante;
        this.numeroSerie = numeroSerie;
        this.fechaAdquisicion = fechaAdquisicion;
        this.ubicacion = ubicacion;
        this.categoriaEquipo = categoriaEquipo;
        this.estado = estado;
    }

    public Equipo() {
    }
}

//-- Tabla Equipos (depende de Ubicaciones, CategoriasEquipos y Estado)
//CREATE TABLE Equipos (
//  -  idEquipo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//   - nombre VARCHAR2(100) NOT NULL,
//  -  tipo VARCHAR2(50),
//  -  fabricante VARCHAR2(100),
//  -  numeroSerie VARCHAR2(100),
//    fechaAdquisicion DATE, +
//    idUbicacion NUMBER NOT NULL, +
//    idCategoria NUMBER NOT NULL, +
//    idEstado NUMBER,  -- Estado del equipo (referencia a la tabla Estado) +
//    CONSTRAINT fk_equipos_ubicaciones FOREIGN KEY (idUbicacion) REFERENCES Ubicaciones(idUbicacion),
//    CONSTRAINT fk_equipos_categorias FOREIGN KEY (idCategoria) REFERENCES CategoriasEquipos(idCategoria),
//    CONSTRAINT fk_equipos_estado FOREIGN KEY (idEstado) REFERENCES Estado(idEstado)
//);