
package com.EquiposMedicos.domain;

import jakarta.persistence.*;

import lombok.Data;

/**
 *
 * @author kcalm
 */
@Data
@Entity
@Table(name = "Equipos")
public class Equipo {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long idEquipo;
    
    @Column(name = "nombre", length = 100, nullable = false)
    private String nombre;
    
    @Column(name = "tipo", length = 50)
    private String tipo;
    
    @Column(name = "fabricante", length = 100)
    private String fabricante;
    
    @Column(name = "numeroSerie", length = 100)
    private String numeroSerie;
    
    @ManyToOne
    @JoinColumn(name = "idEstado")
    private Estado estado; 

    public Equipo() {
    }

    public Equipo(String nombre, String tipo, String fabricante, String numeroSerie, Estado estado) {
        this.nombre = nombre;
        this.tipo = tipo;
        this.fabricante = fabricante;
        this.numeroSerie = numeroSerie;
        this.estado = estado;
    }
}

//-- Tabla Equipos (depende de Ubicaciones, CategoriasEquipos y Estado)
//CREATE TABLE Equipos (
//  -  idEquipo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//   - nombre VARCHAR2(100) NOT NULL,
//  -  tipo VARCHAR2(50),
//  -  fabricante VARCHAR2(100),
//  -  numeroSerie VARCHAR2(100),
//    fechaAdquisicion DATE, +
//    idUbicacion NUMBER NOT NULL, +
//    idCategoria NUMBER NOT NULL, +
//    idEstado NUMBER,  -- Estado del equipo (referencia a la tabla Estado) +
//    CONSTRAINT fk_equipos_ubicaciones FOREIGN KEY (idUbicacion) REFERENCES Ubicaciones(idUbicacion),
//    CONSTRAINT fk_equipos_categorias FOREIGN KEY (idCategoria) REFERENCES CategoriasEquipos(idCategoria),
//    CONSTRAINT fk_equipos_estado FOREIGN KEY (idEstado) REFERENCES Estado(idEstado)
//);