/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.EquiposMedicos.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.LocalDateTime;
import java.util.Date;
import lombok.Data;

/**
 *
 * @author kcalm
 */

@Data
@Entity
@Table(name = "ErroresPorCategoria")
public class ErroresPorCategoria {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long idErrorCategoria;
    
    @Column(name = "fechaRegistro", nullable = false)
    private Date fechaRegistro;
    
    @Column(name = "accion", length = 255, nullable = false)
    private String accion;
    
    @ManyToOne
    @JoinColumn(name = "idCategoria")
    private CategoriaEquipo categoriaEquipo; 
    
    @ManyToOne
    @JoinColumn(name = "idError")
    private Errores errores; 
}
//-- Tabla ErroresPorCategoria (depende de CategoriasEquipos y Errores)
//CREATE TABLE ErroresPorCategoria (
//    idErrorCategoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//    idCategoria NUMBER NOT NULL,
//    idError NUMBER NOT NULL,
//    fechaRegistro DATE NOT NULL,
//    CONSTRAINT fk_erroresporcategoria_categoria FOREIGN KEY (idCategoria) REFERENCES CategoriasEquipos(idCategoria),
//    CONSTRAINT fk_erroresporcategoria_error FOREIGN KEY (idError) REFERENCES Errores(idError)
//);