/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.EquiposMedicos.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.LocalDateTime;
import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

/**
 *
 * @author kcalm
 */
@Data
@Entity
@Table(name = "HistorialUsuarios")
public class HistorialUsuario {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long idHistorial;
    
    @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm") 
    @Column(name = "fechaHora", nullable = false)
    private LocalDateTime fechaHora;

    //private TIMESTAMP fechaHora;
    
    @Column(name = "accion", length = 255, nullable = false)
    private String accion;
    
    @ManyToOne
    @JoinColumn(name = "idUsuario")
    private Usuario usuario; 

    public HistorialUsuario() {
    }

    public HistorialUsuario(LocalDateTime fechaHora, String accion, Usuario usuario) {
        this.fechaHora = fechaHora;
        this.accion = accion;
        this.usuario = usuario;
    }
}


//-- Tabla HistorialUsuarios (depende de Usuarios)
//CREATE TABLE HistorialUsuarios (
//    idHistorial NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//    idUsuario NUMBER NOT NULL,
//    fechaHora TIMESTAMP NOT NULL,
//    accion VARCHAR2(255),
//    CONSTRAINT fk_historial_usuarios FOREIGN KEY (idUsuario) REFERENCES Usuarios(idUsuario)
//);